### ISSUE TITLE
Improper batching

### ISSUE THREAD

**Issue by Beng89** [htgc/fluent-plugin-azureeventhubs#17]
According to the azure [event hubs documentation](https://docs.microsoft.com/en-us/rest/api/eventhub/send-batch-events), the messages endpoint supports batches of events as an array:

```json
[
  { "Body": { ... } },
  { "Body": { ... } }
]
```

 However, this plugin passes an object with a records property:
```json
{
  "records": [
    { ... },
    { ... }
  ]
}
```

I realize that this repo appears to be unmaintained, however, I am unable to open issues against the fork [https://github.com/ChihSeanHsu/fluent-plugin-azureeventhubs-batched](https://github.com/ChihSeanHsu/fluent-plugin-azureeventhubs-batched) so I am opening the issue here. @ChihSeanHsu would you be willing to implement the correct payload in your fork?

EDIT: fixed current payload

**Comment by ChihSeanHsu** [comment]
Hi @Beng89,
I have changed setting to my fork project, and you can post issue to that project now.
I'll try to implement your suggestion, or you can submit a PR to that project if you have time, thanks.

**Comment by ChihSeanHsu** [comment]
Hi @Beng89,
I have changed this request in my fork repo, if there were any problem, please let me know.

**Comment by Beng89** [comment]
@ChihSeanHsu sorry for the delay and thank you for making that update.

I'm not 100% certain as I haven't had a chance to test it, but I believe the `Content-Type` header must be set to `application/vnd.microsoft.servicebus.json` when making a batched request to event hubs.

**Comment by ChihSeanHsu** [comment]
Hi @Beng89,
I have tried it in my dev env, and it can pass to eventhub and other steps behind eventhub.

**Comment by Beng89** [comment]
Perfect, I'll close this issue then, thank you for your time!
